/**
 * The EMIL gallery: captures of the running EMIL applications, taken on
 * 12 September 2026 — the Control Cockpit, screen by screen, and the EMIL Trade
 * terminal.
 *
 * The files are the same captures the EMIL page frames — `public/app/`, as
 * WebP at up to 2560px wide for inspection, with 480px copies in `thumb/` for
 * the strip — so each is stored once. The slug is the app-shot id. Where a capture
 * showed something that is not the site's to publish — an account number, a
 * server address, a bridge token, the private app host in code samples, the
 * owner's name — it was blacked out before it was saved, and `redacted` says so.
 */
export type GalleryShot = {
  slug: string
  /** The screen's own name, as the app labels it. */
  title: string
  /** One line on what matters in the capture. */
  heading: string
  /** The explanation under it: what to look at, and why it is there. */
  body: string
  /** Local time the capture was taken, HH:MM. */
  time: string
  width: number
  height: number
  /** Set only where a gallery mixes capture days. */
  date?: string
  redacted?: boolean
}

export const EMIL_GALLERY_DATE = '12 September 2026'

export const EMIL_GALLERY: readonly GalleryShot[] = [
  {
    slug: 'cockpit',
    title: 'Control Cockpit — Dashboard',
    heading: 'Where EMIL is operated.',
    body: 'The cockpit on arrival: the mode it is in, what the guardian has stopped, the morning brief with its own sourcing line, and the capital, exposure and risk-budget meters underneath.',
    time: '22:17',
    width: 2542,
    height: 1338,
  },
  {
    slug: 'markets',
    title: 'Global Markets',
    heading: 'Every board says where its numbers came from.',
    body: 'Global Markets: nine exchange clocks, the watchlist, and boards for indices, metals, energy, FX reference rates and crypto — each stamped with its provider, its freshness and the time it was fetched.',
    time: '22:17',
    width: 2548,
    height: 1341,
  },
  {
    slug: 'instruments',
    title: 'Instrument Master',
    heading: 'One symbol, however each provider spells it.',
    body: 'The instrument master: one canonical symbol per instrument, what each provider calls it, and whether it carries a research feed, a venue, or both.',
    time: '22:17',
    width: 2557,
    height: 1342,
  },
  {
    slug: 'heatmap',
    title: 'Heatmap & Breadth',
    heading: 'How broad a move really is.',
    body: 'Heatmap and breadth: how much of each group advanced, its average move, and its best and worst name — FX against the dollar, crypto, and the research board.',
    time: '22:18',
    width: 2559,
    height: 1347,
  },
  {
    slug: 'charts',
    title: 'Charts',
    heading: 'Research charts, never an execution price.',
    body: 'Research charting: candles with SMA, EMA, Bollinger and RSI computed inside the cockpit, compare mode, and your own saved levels — labelled delayed research data, never an execution price.',
    time: '22:18',
    width: 2559,
    height: 1329,
  },
  {
    slug: 'company',
    title: 'Company Intelligence',
    heading: 'Fundamentals straight from the filings.',
    body: 'Company intelligence straight from SEC XBRL: eight fiscal quarters of revenue and net income, the balance sheet, and the concept name used for every figure.',
    time: '22:19',
    width: 2559,
    height: 1348,
  },
  {
    slug: 'screener',
    title: 'Equity Screener',
    heading: 'A screener that admits what it is missing.',
    body: 'The equity screener, where a row says what it is still missing rather than guessing: ready, needs a filings scan, or needs a price.',
    time: '22:19',
    width: 2559,
    height: 1342,
  },
  {
    slug: 'news',
    title: 'EMIL News',
    heading: 'Headlines, and why each one matters.',
    body: 'Headlines from open news indexes, each tagged with impact, stance and the instruments it touches, and each carrying one line on why it matters.',
    time: '22:20',
    width: 2559,
    height: 1338,
  },
  {
    slug: 'alerts',
    title: 'Alert Center',
    heading: 'Alerts that inform and never act.',
    body: 'Price alerts: a condition, a threshold and a note saying why the level matters. Alerts are research signals — they never place, modify or cancel anything.',
    time: '22:20',
    width: 2557,
    height: 1344,
  },
  {
    slug: 'arm',
    title: 'ARM / DISARM',
    heading: 'Arming is a deliberate act.',
    body: 'The activation screen: the disclosure, the nine operating modes with what each may and may not do, every limit that will apply, and the acknowledgements that have to be ticked.',
    time: '22:21',
    width: 2557,
    height: 1335,
  },
  {
    slug: 'cards',
    title: 'Trade Cards',
    heading: 'A trade card, with every vote shown.',
    body: 'A trade card: levels, size, monetary risk, the conditions it was read against, the reasons for and against, and every agent vote — including the ones that said no.',
    time: '22:21',
    width: 2544,
    height: 1234,
  },
  {
    slug: 'portfolio',
    title: 'Portfolio & Exposure',
    heading: 'Every account, including the silent ones.',
    body: 'Every linked account in one exposure map, including the ones that are not answering — a stale bridge and a key that is not whitelisted both say so on the row.',
    time: '22:21',
    width: 2559,
    height: 1335,
    redacted: true,
  },
  {
    slug: 'scenario',
    title: 'Scenario & Hedge Simulator',
    heading: 'What a shock would do to the book.',
    body: 'The scenario and hedge simulator: six macro factors on sliders, the linear P&L of every position, and proxy hedges sized against the net factor exposure.',
    time: '22:22',
    width: 2559,
    height: 1333,
  },
  {
    slug: 'council',
    title: 'Agent Council',
    heading: 'Twenty-nine steps before an order exists.',
    body: 'The decision pipeline: the twenty-nine steps a trade has to survive, with the current candidate’s position in it, and the forty agents grouped by what they are for.',
    time: '22:22',
    width: 2554,
    height: 1342,
  },
  {
    slug: 'apihub',
    title: 'Global Markets & API Hub',
    heading: 'Two routes to market, one risk pipeline.',
    body: 'The API hub: connect a broker you already have, or use the native terminal — and every market selected here runs through the same risk pipeline.',
    time: '22:22',
    width: 2559,
    height: 1335,
  },
  {
    slug: 'terminal',
    title: 'EMIL Trade — terminal',
    heading: 'Chart, watchlist and order desk on one surface.',
    body: 'The terminal: chart, watchlist, order desk and open positions on one surface, with the account’s margin state along the bottom.',
    time: '22:23',
    width: 2557,
    height: 1344,
  },
  {
    slug: 'paper',
    title: 'Paper Trading Desk',
    heading: 'A paper desk that states its protections.',
    body: 'The paper desk: sandbox and testnet venues, a ticket that states its own protections — quote age, latency, spread, duplicate window, daily cap — and a journal of what was sent.',
    time: '22:23',
    width: 2556,
    height: 1332,
  },
  {
    slug: 'agentdesk',
    title: 'Agent Paper Desk',
    heading: 'Agents propose. A human confirms.',
    body: 'The agent paper desk, where the council proposes, the guardian checks and sizes deterministically, and a human confirms — to sandbox venues only, with live ones refused in code.',
    time: '22:24',
    width: 2556,
    height: 1338,
  },
  {
    slug: 'backtest',
    title: 'Backtest Engine',
    heading: 'A backtest that grades itself weak.',
    body: 'A backtest that argues with itself: the verdict calls the result thin, names the buy-and-hold it failed to beat, and says the walk-forward has too few folds to judge.',
    time: '22:24',
    width: 2556,
    height: 1350,
  },
  {
    slug: 'options',
    title: 'Options Analytics',
    heading: 'Reading volatility, not predicting it.',
    body: 'Options analytics: ATM implied volatility by expiry, put/call open interest, max pain, skew, and the chain itself.',
    time: '22:24',
    width: 2559,
    height: 1350,
  },
  {
    slug: 'calendar',
    title: 'Calendar & Central Banks',
    heading: 'Central banks, with no rate guessed.',
    body: 'Central-bank state derived from the calendar feed and the latest FRED observations — and a bank with no decision in the window shows no rate rather than a guess.',
    time: '22:25',
    width: 2559,
    height: 1338,
  },
  {
    slug: 'calendar-menu',
    title: 'Calendar & Central Banks — full menu',
    heading: 'Every surface, one menu away.',
    body: 'The same monitor with the whole cockpit menu open down the side — every surface from the paper desks to the organisation settings one click away, with Close All and Emergency Stop pinned beneath them.',
    time: '22:53',
    width: 2559,
    height: 1336,
  },
  {
    slug: 'journal',
    title: 'Trade Journal',
    heading: 'Graded on process, not on outcome.',
    body: 'The journal grades the process, not the outcome: an incomplete entry is reviewed, given a process grade, told exactly what was missing, and flagged — with the advice that an incomplete log is itself a process error.',
    time: '22:53',
    width: 2559,
    height: 1347,
  },
  {
    slug: 'risk',
    title: 'Risk Management',
    heading: 'Sizing that starts at the stop.',
    body: 'Risk-first sizing, where the calculated lot is cut to the exposure ceiling and says so — next to nine circuit breakers each showing its current value, its limit and what it does on trip.',
    time: '22:54',
    width: 2559,
    height: 1350,
  },
  {
    slug: 'capital',
    title: 'Capital & Performance',
    heading: 'Capital in layers, with floors that hold.',
    body: 'Capital in layers: protected capital with a floor it is never risked below, a profit floor that locks banked gains, and an equity curve with the drawdown laid over it.',
    time: '22:54',
    width: 2535,
    height: 1345,
  },
  {
    slug: 'strategycenter',
    title: 'Strategy Center',
    heading: 'Champion against challenger.',
    body: 'Champion against challenger, and a promotion pipeline a strategy has to walk: research, backtest, paper, restricted live, production — never on backtest results alone.',
    time: '22:54',
    width: 2554,
    height: 1338,
  },
  {
    slug: 'strategylab',
    title: 'Strategy Lab',
    heading: 'Estimates labelled as estimates.',
    body: 'The lab, with its data mode declared: estimates are labelled as estimates, a candidate missing a rule is marked incomplete rather than completed by guesswork, and every stage of the pipeline is its own tab.',
    time: '22:55',
    width: 2556,
    height: 1342,
  },
  {
    slug: 'teach',
    title: 'Teach EMIL',
    heading: 'Everything it reads is a hypothesis.',
    body: 'Teaching it: public material only, every statement classified and attributed to its exact source, contradictions checked against what it already holds, and the result stored as an untested hypothesis.',
    time: '22:55',
    width: 2559,
    height: 1345,
  },
  {
    slug: 'trust',
    title: 'Trust & Metacognition',
    heading: 'High confidence cannot override low trust.',
    body: 'Confidence in a setup and trust in the environment are separate numbers, and high confidence can never override low trust — the example shows an 82% setup declined at 46% trust.',
    time: '22:56',
    width: 2559,
    height: 1339,
  },
  {
    slug: 'connect',
    title: 'Connect Your Platform',
    heading: 'Your own platform, mirrored read-only.',
    body: 'Bringing your own platform in: MetaTrader mirrors read-only, alerts arrive by private webhook, statements import into the journal — and nothing is ever sent back to your terminal.',
    time: '22:56',
    width: 2559,
    height: 1339,
    redacted: true,
  },
  {
    slug: 'developers',
    title: 'Developers & Integrations',
    heading: 'Scoped keys, and a sandbox that cannot trade.',
    body: 'Keys with scopes, an optional IP allow-list and an expiry; sandbox keys that cannot link a broker at all; quickstarts in curl, JavaScript and Python.',
    time: '22:57',
    width: 2559,
    height: 1345,
    redacted: true,
  },
  {
    slug: 'integrations',
    title: 'Integrations Directory',
    heading: 'An integrations list, labelled honestly.',
    body: 'The integration directory, labelled honestly: live means built and working here, and via REST means it works through the API today without a listing in that vendor’s marketplace.',
    time: '22:57',
    width: 2556,
    height: 1339,
  },
  {
    slug: 'datafeed',
    title: 'Your Data Feed',
    heading: 'Your data stays yours.',
    body: 'Your own pushed data, isolated to your account and never mixed with the research feeds — quotes, orders and equity points in, summaries out.',
    time: '22:57',
    width: 2554,
    height: 1344,
    redacted: true,
  },
  {
    slug: 'settings',
    title: 'Settings & Permissions',
    heading: 'Permissions as switches, and an export of everything.',
    body: 'Permission grants as switches with the risk profile beside them, an export of everything in one file, and a retention policy that says how long each kind of record is kept.',
    time: '22:58',
    width: 2559,
    height: 1339,
  },
  {
    slug: 'organization',
    title: 'Organization',
    heading: 'Running EMIL as a team.',
    body: 'Running it as a team: roles, client books, a recommendation workflow, desk controls, approvals and a tamper-evident archive.',
    time: '22:58',
    width: 2554,
    height: 1332,
    redacted: true,
  },
]

/**
 * The EMIL Trade gallery: the trading platform, captured on 14 September 2026,
 * opening on the terminal capture the EMIL gallery also carries. Files follow
 * the same `public/app/` layout, prefixed `et-`. Blacked out before saving:
 * the trader ID in the header, and the video call's session ID. The live TV
 * frame is blurred, because the broadcast is not the site's to republish.
 */
export const EMIL_TRADE_GALLERY_DATE = '14 September 2026'

export const EMIL_TRADE_GALLERY: readonly GalleryShot[] = [
  {
    slug: 'terminal',
    title: 'EMIL Trade — terminal',
    heading: 'Every market, one window.',
    body: 'The EMIL Trade terminal: market watch on the left, the chart in the middle, the order desk with open positions underneath, and the account’s balance, equity and margin pinned along the bottom.',
    time: '22:23',
    date: '12 September 2026',
    width: 2557,
    height: 1344,
  },
  {
    slug: 'et-trading-menu',
    title: 'Trading menu',
    heading: 'The whole platform, one menu away.',
    body: 'The Trading menu: the terminal, ABIN, live TV, the traders’ chat floor, the EMIL Control Cockpit, markets, orders and positions, the EA Builder, the AI Strategy Lab and AI signals.',
    time: '11:05',
    width: 2557,
    height: 1339,
    redacted: true,
  },
  {
    slug: 'et-ticket',
    title: 'Quick trade ticket',
    heading: 'A ticket that asks how sure you are.',
    body: 'One ticket for both charts: lots, risk presets from 0.5% to 5%, stop and target, a “Sure?” confidence setting, and the pip value and margin required before you send. Beneath it, confirm-before-execution, auto-protect with a default stop and target, partial closes from 10% to 100%, and close all, close profit, close loss or cancel pending.',
    time: '11:05',
    width: 2550,
    height: 1344,
    redacted: true,
  },
  {
    slug: 'et-alerts',
    title: 'Alerts',
    heading: 'Alerts on price, conditions and the account.',
    body: 'Price alerts above or below a level, with a note; condition alerts such as an EMA cross, checked on closed bars; and account and risk alerts such as the spread widening past a limit. Anything that fires also lands in the NEXUS Alert Center.',
    time: '11:07',
    width: 2559,
    height: 1336,
    redacted: true,
  },
  {
    slug: 'et-nexus',
    title: 'NEXUS AI trade assistant',
    heading: 'A trading companion beside the chart.',
    body: 'NEXUS opens as a side panel. Ask it anything, have it analyse a setup, review your positions or coach your trading psychology, or use its one-tap actions — Entry Zone, Mark Zone on Chart, Manage Trades. Its Active switch and alerts sit at the top, and every answer is marked as AI analysis, not financial advice.',
    time: '11:04',
    width: 2548,
    height: 1351,
  },
  {
    slug: 'et-live-tv',
    title: 'Live TV and trader tools',
    heading: 'Financial television, docked beside the chart.',
    body: 'The Tools panel: pip, position size, margin, profit / loss and risk / reward calculators, with Finance TV Live and market headlines underneath, so the broadcast keeps playing while you work the chart. The broadcast frame is blurred here.',
    time: '11:04',
    width: 2557,
    height: 1344,
    redacted: true,
  },
  {
    slug: 'et-video-chat',
    title: 'Video chat',
    heading: 'Talk to your broker, face to face.',
    body: 'Support video chat inside the terminal: start a call with your broker for live support, with microphone, camera and screen-sharing controls, and a session ID for the call.',
    time: '11:05',
    width: 2557,
    height: 1330,
    redacted: true,
  },
  {
    slug: 'et-scanner',
    title: 'Trade Scanner',
    heading: 'Signals graded in public, wins and losses alike.',
    body: 'Twenty instruments on a live feed with four levels of authority — Off, Signal Only, Manual Confirmation, Full Auto. Rules go in as plain language, the engine answers questions about itself, filters cover asset class, trading style, direction and score, and every signal card carries entry, stop, three targets and a confidence score. Emergency Stop sits at the top.',
    time: '11:07',
    width: 2544,
    height: 1333,
    redacted: true,
  },
  {
    slug: 'et-hedge',
    title: 'AI Correlation Hedging Engine',
    heading: 'A hedging engine that refuses a weak hedge.',
    body: 'Relationships computed live, never hard-coded. Auto Hedge starts monitor-only, its rules are written in plain language, and when no reliable hedge exists — as here for US30 — it says so and names the candidates it rejected, above the strongest live relationships ranked by correlation.',
    time: '11:06',
    width: 2547,
    height: 1336,
    redacted: true,
  },
  {
    slug: 'et-shield',
    title: 'Shield — Trader Protection',
    heading: 'Rules set in calm moments, enforced in bad ones.',
    body: 'Self-imposed rules that gate new orders only and bind every order surface, EAs included: presets, all on or all off, today’s P&L, trade count and loss streak, then capital protection — a daily loss circuit-breaker, an equity floor kill switch, a risk-per-trade cap, mandatory stop-loss, a margin early-warning ladder and a correlation guard.',
    time: '11:08',
    width: 2550,
    height: 1333,
    redacted: true,
  },
  {
    slug: 'et-abin',
    title: 'ABIN',
    heading: 'Ask the market in plain words.',
    body: 'The Advanced Brokerage Intelligence Network: search or command in plain language, in English or Hindi, over a cross-asset board that labels each instrument’s trend and volatility, with global session status and the top scanner opportunities beneath. Opening ABIN grants no trading authority. Demo account.',
    time: '11:07',
    width: 2557,
    height: 1335,
    redacted: true,
  },
  {
    slug: 'et-portfolio',
    title: 'Portfolio menu',
    heading: 'Your account, from overview to journal.',
    body: 'The Portfolio menu: a dashboard of KPIs, equity and performance analytics, closed-trade history, the wallet for deposits and withdrawals, and the trade journal for notes and insights.',
    time: '11:06',
    width: 2554,
    height: 1348,
    redacted: true,
  },
  {
    slug: 'et-tools',
    title: 'Tools menu',
    heading: 'Research and support, one menu away.',
    body: 'The Tools menu: price and event alerts, the economic calendar, the market news feed, the TradingView widget suite, the market heatmap, education, and support with help tickets.',
    time: '11:06',
    width: 2554,
    height: 1344,
    redacted: true,
  },
]

export const galleryFull = (shot: GalleryShot) => `/app/${shot.slug}.webp`
export const galleryThumb = (shot: GalleryShot) => `/app/thumb/${shot.slug}.webp`
