import { ENGINES } from '../engines'
import { specChecksum, type EmilStrategySpec } from '../spec'

/** A file name from the strategy name: letters, digits and underscores. */
export function fileBaseName(spec: EmilStrategySpec): string {
  const base = spec.name
    .normalize('NFKD')
    .replace(/[^A-Za-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 48)
  return base || 'EMIL_Strategy'
}

/**
 * ASCII-only text for MQL5 sources, which MetaEditor may read in a legacy
 * codepage: accents are folded, dashes simplified, anything else becomes "?".
 */
export function toAscii(text: string): string {
  return text
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[–—]/g, '-')
    .replace(/[^\x20-\x7E]/g, '?')
}

/** A number as source code: integers bare, doubles always with a decimal point. */
export function formatNumber(value: number, type: 'int' | 'double'): string {
  if (type === 'int') return String(Math.round(value))
  const text = String(value)
  return /[.eE]/.test(text) ? text : `${text}.0`
}

/**
 * The comment block every generated file starts with: what it is, where it
 * came from, and the risk statement. `marker` is the line-comment token.
 */
export function codeHeader(spec: EmilStrategySpec, brand: string, marker: string, ascii = false): string {
  const engine = ENGINES[spec.engine]
  const lines = [
    `${spec.name} — generated by ${brand}`,
    '',
    `Engine:     ${engine.label} (${spec.engine})`,
    `Timeframe:  ${spec.timeframe}    Symbols: ${spec.symbols.join(', ')}`,
    `Strategy:   ${spec.id} v${spec.version}    Checksum: ${specChecksum(spec)}`,
    '',
    'Implements the same rule and the same indicator formulas as the EMIL Trade',
    'EA engine: evaluated on closed bars, acts when the regime changes, fixed lot,',
    'ATR(14) stop-loss and take-profit. Indicator values converge with EMIL Trade',
    'once enough history has loaded.',
    '',
    'Test on a demo account before any live use. Trading leveraged products',
    'carries a high level of risk to capital; past and backtested performance is',
    'not indicative of future results.',
  ]
  return lines
    .map((line) => (ascii ? toAscii(line) : line))
    .map((line) => (line ? `${marker} ${line}` : marker))
    .join('\n')
}
